### ISSUE TITLE
Create TypeCobol web site

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1379]
## Goal is to present different aspects of TypeCobol:

- [ ] Present "The TypeCobol Initiative":
Why TypeCobol ? // License // Roadmap // FAQ // Limitations // Concepts // References
- [ ] Present the language":
Types // Operators // Procedurals // Functions // Namespaces // Errors
- [ ] Present examples:
TypeCobol .tcbl // Cobol .cbl
- [ ] Present API:
Objects and Methods
- [ ] Present architecture
- [ ] Perspectives for later:
Control flow graphs // Data flow analysis

**Comment by NicolasStr** [comment]
Objective is to create a frontpage for the project with Reactjs/Gatsby (gh-pages branch or another repo) and create a readthedocs.io doc (docs folder) so that we can update the doc while merging a version to master.

# Question is now:
Should we create another repo for the frontpage with a CI/CD on [Netlify or Github Pages]
Or, we can add a gh-pages branch on this repo and use Github Pages.

**Comment by smedilol** [comment]
Let's go for another repo, so we can also generate doc for LanguageServerRobot.

**Comment by NicolasStr** [comment]
Ok, creating a repo named typecobolteam.github.io should now do the trick for Github to generate the domain. I will fork and work on it when it's done.

**Comment by smedilol** [comment]
Ok done:
https://github.com/TypeCobolTeam/typecobolteam.github.io

**Comment by smedilol** [comment]
WebSite is now ready.
See https://github.com/TypeCobolTeam/TypeCobol-WebSite/issues/54 to migrate content from our wiki to the web site.
