### ISSUE TITLE
Visibility of typedef can be missing

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1392]
**LINK WITH #1343 AND #1081**
Currently we only have a visibility enum with public or private.
The goal of this issue is to add a new value to the enum `default` (or no explicit visibility).
But the current behavior must remains unchanged. It means that default is always equals to private.
#1081 will change this behavior and use `default` as a separated value.

**Comment by fm-117** [comment]
How should `TypeCobol.Compiler.Nodes.Documentation` be handled ? The documentation declares a visibility which is nullable. Using the new Default visibility, the nullable is not required anymore but this changes the way documentation is rendered. See [class here](https://github.com/TypeCobolTeam/TypeCobol/blob/develop/TypeCobol/Compiler/Nodes/Documentation.cs).

**Comment by mayanje** [comment]
As I can read it handles Visibility in presence of CodeElements of type DataTypeDescriptionEntry and FunctionDeclarationHeader ok, so I think here the code must be adapted for first check if the Visibility is null or not and to maintains also the case with no Visibility set here, for documentation purpose, because the documentation must also reflect the fact that there was no visiblity set.

**Comment by mayanje** [comment]
ok, as we talked the Visibility property has an attribute [DataMember(EmitDefaultValue = false)], thus if the Visibility value is set to the default value then nothing will be displayed, thus the nullable modifier is not necessary here.

**Comment by fm-117** [comment]
As discussed, the nullable is not required anymore since the lack of modifier is now expressed with the 'Default' value of the enum. This won't affect the result of serialization because 'Default' will indeed be defined as the default value of the enum (value = 0) and the EmitDefaultValue=false option is used during serialization. Test data will have to be updated though since textual value of Visibility is used regardless it is default or not.

**Comment by fm-117** [comment]
Instead of 'Default' visibility, we should name it 'Local' visibility as opposed to Global in COBOL spec.
