### ISSUE TITLE
Completion on half written words

### ISSUE THREAD

**Issue by maxime645** [TypeCobolTeam/TypeCobol#1440]
**Describe the bug**
The completion doesn't work fine when the type we try to complete is half written and the node not properly ended.

**To Reproduce**
(Type)Cobol code that cause the bug : (if any)
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. Callee.
      
       DATA DIVISION.
       working-storage section.
      
       01 STR.
           05 DATA1 PIC X.
           05 DATA2 TYPE B
           05 FILLER PIC X.
      
       PROCEDURE DIVISION.
      
       END PROGRAM Callee.
```
Try to complete variable DATA2 to "Bool".
When the B is written and we call autocompletion, it won't find anything. Yet, when nothing is written and call autocomplete, it gives all the possibilities.
After first analysis, there is no node associated to the line "05 DATA2 TYPE B"

**Expected behavior**
Autocompletion should return the compatible types.

**Comment by fm-117** [comment]
This is not a completion bug but rather a parsing problem. In the given example :
- without the `B` after `TYPE`, CUP will produce all expected nodes
- with `B` after `TYPE`, CUP parser stops after DATA1 and no other nodes are produced (no DATA2, no PROCEDURE DIVISION, no END PROGRAM)

Without nodes for the matching token/codeelement, no completion can be performed.
It means that this issue is related to CUP and the way it handles errors and sometimes stops the whole process.

**Comment by fm-117** [comment]
In fact this is more related to ANTLR which produces wrong CodeElements (then CUP has trouble building nodes with such input).

When reading tokens, ANTLR comes to an error at `05 DATA2 TYPE B` because there is no PeriodSeparator. The problem here is that the Scanner will produce an `IntegerLiteral` token instead of a `LevelNumber` for the `05` of the next line. From there, the parsing seems to be broken and as previously explained, the completion is broken as well. Note that the completion works as expected if we add a `.` after `TYPE B` or if there is no additional data declaration after `TYPE B` (because in both cases the next token will be correctly recognized).

I could not find a way to disambiguate between IntegerLiteral and LevelNumber when there is no previous PeriodSeparator to clearly tell that a new data declaration was expected. We could add special cases in [MultilineScanState.AtBeginningOfSentence](https://github.com/TypeCobolTeam/TypeCobol/blob/d6a78b3ff7fc618d84b005c89a01e9cbe495160e/TypeCobol/Compiler/Scanner/MultilineScanState.cs#L464) but the code may become cumbersome...

We need to discuss more about that case.
