### ISSUE TITLE
Don't refresh opened files if RefreshCustomSymbols fails

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1442]
**Describe the bug**
A user got a bug when COPY was loaded because it's COPY folder was missing.

He got the following error:
![image](https://user-images.githubusercontent.com/13764482/63947936-1fce2280-ca78-11e9-9f2a-56eb20cfe021.png)
![image](https://user-images.githubusercontent.com/13764482/63947954-278dc700-ca78-11e9-9e1c-8e4ed660bc9f.png)

Try to reproduce the problem.

**To Reproduce**
Delete your copy folder and start LSP.

**Expected behavior**
At least a clear error message to help the user understand the problem.

**Comment by fm-117** [comment]
NullReferenceException occurs at line 189 in Workspace.cs on _customSymbols field which is null :
```
 var matchingPgm =
                _customSymbols.Programs.Keys.FirstOrDefault(
                    k => k.Equals(inputFileName, StringComparison.InvariantCultureIgnoreCase));
```
_customSymbols is not set because of error during RefreshCustomsymbols.
This code is part of #583 and happen only with EI_CUSTOM_RULES, the test is also performed in LoadDependencies itself so it seems it is redundant to have it both in Workspace and LoadDependencies. @smedilol do you confirm ?

**Comment by fm-117** [comment]
Nevermind, the code is duplicated to handle the opening of new files in LanguageServer.
