### ISSUE TITLE
Compiler directing statements

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#149]
Compiler directing statements seem processed by the preprocessor (in `CompilerDirectiveBuilder`).
However, whereas these statements don't impair CodeElements grammar parsing at all, they raise syntax errors in ProgramClass grammar.

**Comment by wiztigers** [comment]
Doesn't work:
```cobol
CONTINUE
SKIP3.
```

Work:
```cobol
SKIP3.
```

```cobol
CONTINUE.
SKIP3.
```

```cobol
CONTINUE
SKIP3
CONTINUE.
```

Replacing `CONTINUE` by `PERFORM procedurename` yields the same results.

**Comment by wiztigers** [comment]
@laurentprudhon , any ideas about why some compiler directing statements like `SKIP` make the ProgramClass grammar complain, whereas CodeElements grammar doesn't scoff at them ?
What happens can be tested with what I committed in 56c82f191919a6ff94bc9eb5f0e1c39a8c5b68f5 : the test should pass but does not.

**Comment by laurentprudhon** [comment]
Ok, I will fix this this weekend : my guess is that I didn't correctly filter the token types in the token source for the last phase of parsing

**Comment by laurentprudhon** [comment]
Your test program is invalid, the compiler behavior is correct in this case.

You write for example :
PROCEDURE DIVISION.
SKIP-01. => paragraphName
  CONTINUE => continueStatement
  SKIP3. => compiler directing statement, this whole line is invisible to the ProgramClass paser
<< here a separator period is missing to end the sentence >>
SKIP-02. => paragraphName 
<< you can not start a new paragraph here, because the last sentence was not finished >>

Reference text for SKIP statement p545 : 
SKIP1, SKIP2, or SKIP3 can be written anywhere in either Area A or Area B, and can be terminated with a separator period. It must be the only statement on the line.

Reference text for paragraph syntax p253 : 
Paragraph 
A paragraph-name followed by a separator period, optionally followed by one or more sentences.
!! Paragraphs must be preceded by a period because paragraphs always follow either the IDENTIFICATION DIVISION header, a section, or another paragraph, all of which must end with a period. !!
Sentence 
One or more statements terminated by a separator period.

**Comment by wiztigers** [comment]
Thanks to you @laurentprudhon, I have a better understanding now.

However, I'm not sure the test is invalid : it mimicks real production code.

The problem seems to be that the compiler directing statement as long as the period separator (if any) are always made invisible to the ProgamClass parser. As the period is always "consumed", if the compiler directing statement is the last of the paragraph _AND_ not alone in its sentence, the paragraph won't end with a period as required and we'll thus have a syntax error.

Shouldn't the period ending a compiler directing statement be left at the disposal of the ProgramClass parser in all cases, _except if the compiler directing statement is the only statement in its sentence_ (so we don't have two periods directly following one another) ?

In other terms,
**CASE 1**
if before filtering we have :
```cobol
PARAGRAPH1.
  CONTINUE
  SKIP3.
PARAGRAPH2.
```
after filtering we currently have :
```cobol
PARAGRAPH1.
  CONTINUE
PARAGRAPH2.
```
(the period after `SKIP3` is "consumed", and it's bad)
thus, after "filtering" we *should* have :
```cobol
PARAGRAPH1.
  CONTINUE
  .
PARAGRAPH2.
```

**CASE 2**
If before filtering we have :
```cobol
PARAGRAPH1.
  SKIP3.
  CONTINUE.
PARAGRAPH2.
```
after filtering we currently have  :
```cobol
PARAGRAPH1.
  CONTINUE.
PARAGRAPH2.
```
(the period after `SKIP3` is "consumed", and it's good)
