### ISSUE TITLE
Codegen : FILLER is lost

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1521]
**Describe the bug**
See codegen test IndexesAndAnonymousDataDef.rdz.tcbl
For array TableWithFillerArray, the filler is lost in codegen.

**To Reproduce**
(Type)Cobol code that cause the bug : (if any)
```cobol
       01 ElementType TYPEDEF STRICT.
          05 item-4 PIC X.
       01 TableWithFillerArray.
          05 FILLER Type ElementType
             OCCURS 10 INDEXED BY Idx-InFillerArray.
```

Codegen produces:
```cobol
       01 TableWithFillerArray.
      *   05 FILLER Type ElementType
      *      OCCURS 10 INDEXED BY Idx-InFillerArray.
          05 
             OCCURS 10 INDEXED BY Idx-InFillerArray.
           06 item-4 PIC X.
```

**Expected behavior**
Keep FILLER
```cobol
       01 TableWithFillerArray.
      *   05 FILLER Type ElementType
      *      OCCURS 10 INDEXED BY Idx-InFillerArray.
          05 FILLER
             OCCURS 10 INDEXED BY Idx-InFillerArray.
           06 item-4 PIC X.
```

**Comment by fm-117** [comment]
As discussed with @mayanje, we should look at `TypedDataNode.CreateDataDefinition` to check how FILLER elements are currently handled.

**Comment by fm-117** [comment]
@sarterbe points out that FILLER or Anonymous are exactly the same (both semantically and at runtime). @smedilol do you confirm that we need to change codegen ? Note that in pure Cobol statements, FILLER keyword is not lost so the generated source remains faithful to the original source.

**Comment by smedilol** [comment]
@fm-117 Ok, I thought that initialize had a different behavior between filler and anonymous.
So ok, to postpone to issue.
But I still want to keep this issue open, because we need to produce clean code and keep the existing as much as possible.

**Comment by fm-117** [comment]
As discussed together, there is no need to implement this.

I'd like to note a problem in `CodeElementCheckers.cs` at [line 25](https://github.com/TypeCobolTeam/TypeCobol/blob/e2530c6e38dd3939aaf54c889560de7df36246ec/TypeCobol/Compiler/Diagnostics/CodeElementCheckers.cs#L25) : currently the `Filler` SyntaxProperty in `CommonDataDescriptionAndDataRedefines` is never null and with a true value when FILLER keyword is present or when data has no name. Therefore the test at line 25 is always false because we are testing for nullity of name before.
The diagnostic 

> Data name or FILLER expected

 is never issued so we can safely remove this code during future developments.
