### ISSUE TITLE
Attach End-*** statements to correct parent node

### ISSUE THREAD

**Issue by rooksdo** [TypeCobolTeam/TypeCobol#1677]
**Description**

Attach End-*** statements to correct parent node.

For example in the following code End-Evaluate seems to be attached to IF node:

```cob
Evaluate true
   When COND-1
      IF A = B
End-Evaluate
```

**Comment by fm-117** [comment]
Could not reproduce the bug with this sample :

```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. DVZZMFT0.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 A PIC X.
       01 B PIC X.
       01 Conditions PIC X.
          88 COND-1 VALUE 'V'.
       PROCEDURE DIVISION.
           EVALUATE TRUE
           WHEN COND-1
           IF A = B
      *    DISPLAY 'A equals B'
           END-EVALUATE
           .
       END PROGRAM DVZZMFT0.
```

It works as expected either with the DISPLAY statement commented or not. Without DISPLAY inside IF, the compiler will issue an error because empty IFs are not allowed. With DISPLAY statement inside IF, END-EVALUATE is correctly attached to parent EVALUATE statement.

Do you have any other sample that could help reproduce the problem ?

**Comment by fm-117** [comment]
We should wait for #1719 to be merged before checking the behavior.

**Comment by rooksdo** [comment]
To be closed.
