### ISSUE TITLE
Exception on trying to add an element with same key

### ISSUE THREAD

**Issue by rooksdo** [TypeCobolTeam/TypeCobol#1687]
See #1634

```Cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. DVZS0OSM.
       PROCEDURE DIVISION.
       declare procedure Toto.
       end-declare.
       declare procedure Toto.
       end-declare.
                call 
               GOBACK
               .
       END PROGRAM DVZS0OSM.
```
And ask completion after `call`.

![image](https://user-images.githubusercontent.com/57907033/76094926-b9e0cb80-5fc3-11ea-946b-a9d572d527d0.png)

Maybe it's related to line:
`functionDeclarationSignatureDictionary.Add(signatureInformation, proc);`
Protect for duplicate on this line.

**Comment by delevoye** [comment]
@smedilol @mayanje @rooksdo @fm-117 
In this case, elements with the same key are added to a Dictionary and it causes the exception. The exception is raised because the program above is wrong (duplicate declaration of procedure Toto).
What is the expected solution to avoid exception?
- Add a distinctive element to `SignatureInformation` (e.g. an ID);
- Not adding the element if it is already present and add a Diagnostic;
- Something else?

**Comment by smedilol** [comment]
I suggest the same behavior as Visual Studio:
- Not adding the element if it is already present.

There is already a Diagnostic if the procedure declaration is duplicated.
