### ISSUE TITLE
Export generation shifts declaration to area A

### ISSUE THREAD

**Issue by rooksdo** [TypeCobolTeam/TypeCobol#1770]
Consider the following type declaration with the numeric variable declared on two separate lines :

```cob
       01 numCOMP typedef strict public.
         05 pic 9
            comp-3.
```

Export generation gives the following result with the end of declaration "comp-3" in area A instead of being in area B.
```cob
       01 numCOMP typedef strict public.
         05 pic 9
         comp-3.
```

**Comment by fm-117** [comment]
the problem lies here : https://github.com/TypeCobolTeam/TypeCobol/blob/fc753341d030294f9f2f91e5cd18984b38cf01bc/Codegen/src/Generators/SignaturesGenerator.cs#L151-L168

This code is designed to separate multiple _instructions_ originally written in a single line into several lines but it does not work for instructions that span several lines...

**Comment by smedilol** [comment]
Won't fix as TypeCobol language is no longer supported.
