### ISSUE TITLE
Exception on incomplete IF condition

### ISSUE THREAD

**Issue by rooksdo** [TypeCobolTeam/TypeCobol#1883]
### Description

An exception is fired when an incomplete IF condition statement is present in the COBOL source code.

**Sample**
```cob
       IDENTIFICATION DIVISION.
       PROGRAM-ID. Pgm.
       ENVIRONMENT DIVISION.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       PROCEDURE DIVISION.
       DECLARE PROCEDURE Proc1
           INPUT  O PIC X
           OUTPUT R PIC X.
       data division.
       working-storage section.
       procedure division.
           if O
       END-DECLARE.
       END PROGRAM Pgm.
```

![image](https://user-images.githubusercontent.com/57907033/107665909-35e09a80-6c8e-11eb-993f-751f0fb971d1.png)

**Comment by fm-117** [comment]
The exception is thrown from here:
https://github.com/TypeCobolTeam/TypeCobol/blob/633861edacf6d3a78bd26a3ecbf6773e74517784/TypeCobol/Compiler/Diagnostics/CrossChecker.cs#L413
`dataDefinition.SemanticData` is null because the incomplete `IF` breaks the node phase building and no semantic data is created for procedure parameters.

To fix this, move the semantic data creation for parameters into `StartFunctionDeclaration` instead of `EndFunctionDeclaration`.
See https://github.com/TypeCobolTeam/TypeCobol/blob/633861edacf6d3a78bd26a3ecbf6773e74517784/TypeCobol/Compiler/Domain/ProgramSymbolTableBuilder.cs#L253 and https://github.com/TypeCobolTeam/TypeCobol/blob/633861edacf6d3a78bd26a3ecbf6773e74517784/TypeCobol/Compiler/Domain/ProgramSymbolTableBuilder.cs#L287
@mayanje, do you remember why we chose to create semantic data at the end ?

**Comment by mayanje** [comment]
It seems that there's no reason to perform data creation for parameters in EndFunctionDeclaration rather than in StartFunctionDeclaration.

**Comment by fm-117** [comment]
Ok good, moving the semantic data creation part to `StartFunctionDeclaration` will fix this issue then.
