### ISSUE TITLE
Lsp server : Not allow outline option to be changed by configuration change.

### ISSUE THREAD

**Issue by mayanje** [TypeCobolTeam/TypeCobol#1920]
In v1.5.1 the outilne option can be changed thru configuration changed notification.
This behavior is not compatible with TypeCobol plugin v1.4, because now the outline view is no longer displayed.
So we should disable this possibility.

We should disable this option until TypeCol Plugin v1.5.
Because we need to have this option disabable, for LSR tests options without outline.
With CobolEditEI, this option is enabled only for the Team.

So the solution is to introduce a -team option, so that tis option will be taken in acount only if the -team option is also specified.

**Comment by smedilol** [comment]
The option `-team` is not correct. It's not because currently our IDE restrict an option for our team that it will remains like this forever.
And a custom behavior of our private IDE should not influence how the server works.
The correct solution is to enable the Outline by default (like v1.4) and add a new option to disable the outline if needed.

This way, if another team is allowed to disable the outline, the server will not be impacted.
