### ISSUE TITLE
System.OverflowException with big numeric value

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#2144]
**Describe the bug**
`VALUE +99999999999999999,99` causes an OverflowException .
![image](https://user-images.githubusercontent.com/13764482/154959499-7299ae9b-353a-42cb-b91b-79ad95a6fa50.png)

**To Reproduce**
(Type)Cobol code that cause the bug : (if any)
```cobol
       CBL DATA(31) ARITH(EXTEND)
       IDENTIFICATION DIVISION.
       PROGRAM-ID. MyPGM.
      
       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       SOURCE-COMPUTER. IBM-370.
       SPECIAL-NAMES. DECIMAL-POINT IS COMMA.
      
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01  MNT-MAX                  PIC S9(17)V99
                                    VALUE +99999999999999999,99.
      
       END PROGRAM MyPGM.
```

**Expected behavior**
No error.

**Comment by fm-117** [comment]
To solve this, we could use `BigInteger` type for `IntegerValue` of `DecimalLiteralTokenValue` (and optionally `long` instead of `int` for `DecimalDigits`).
So:
- Check cobol specs for maximum size of decimal digits to know if we have to switch to `long` type
- Change to `BigInteger` and update usages

**Comment by mayanje** [comment]
Voir aussi utiliser le type C# decimal
