### ISSUE TITLE
Wrong syntax tree in SEARCH containing empty when

### ISSUE THREAD

**Issue by laabidiHend** [TypeCobolTeam/TypeCobol#2147]
Problem in the construction of the  syntax tree.
 When search with no condition causes a wrong diagnostic .
The problem is in the whenTest and the whenTestNoEvaluate.

https://github.com/TypeCobolTeam/TypeCobol/blob/e4eb6f4dbd4f9e95f8292cefc07f942e968a84a2/TypeCobol.Test/Parser/Programs/Cobol85/WhenTest.rdzMix.txt#L28-L38

**Comment by fm-117** [comment]
At line 28 in `WhenTest.rdzMix.txt`, the diagnostic is wrong because the SEARCH actually has several WHEN children.
An empty WHEN is translated by ANTLR to a WhenCondition CodeElement, however CUP grammar does not allow WhenCondition as child of Search so from this point the syntax tree is broken.

Some ideas:
- find a way to recover from error in CUP grammar
- redesign the grammar to allow empty WHENs in Search
  - this probably means unifying When for EVALUATE with When for SEARCH

**Comment by fm-117** [comment]
Fixed by #2312.
