### ISSUE TITLE
WHENEVER

### ISSUE THREAD

**Issue by laabidiHend** [TypeCobolTeam/TypeCobol#2246]
Description

The [Whenever](https://www.ibm.com/docs/en/db2-for-zos/12?topic=statements-whenever) statement statement specifies the host language statement to be executed when a specified exception condition occurs.

This implies:

- To write the ANTLR grammar
- To write the CUP grammar
- Building the Whenever Statement CodeElement
- Building the Whenever Node
- Creating the corresponding Sql Object
- Making corresponding CodeElement, Node and SqlObject classes visitable
- Write test unit

**Comment by fm-117** [comment]
- `NOT` and `CONTINUE` are reserved words so no need to redefine them as contextual keywords
- Please respect C# naming conventions
  - enum members use the Pascal-case naming scheme so `NotFound`, `SqlError`, `SqlWarning`, same goes for `Continue` or `GoTo`
  - properties also use Pascal-case so `HostLabel` instead of `Host_Label`
- To improve the naming a bit, I suggest `BranchingType` instead of `NextStatementType` (enum and property) and `TargetSectionOrParagraph` instead of `HostLabel`
- I'm not sure how the priority works in ANTLR syntax so your proposal may work but is difficult to read in the last part. You can split it into two rules to improve readability.

```
whenEverStatement: SQL_WHENEVER (SQL_NOT sqlFound | sqlError | sqlWarning) (SQL_CONTINUE | sqlGotoHostLabel);
sqlGotoHostLabel: (SQL_GOTO | SQL_GO SQL_TO) ColonSeparator? hostLabel=UserDefinedWord;
```
