### ISSUE TITLE
COPY Procedure may produce parsing error

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#235]
** DUPLICATE OF #312 **
In certain cases, COPY parsing can produce errors:
Giving this COPY:

``` cobol
move c to d
```

The following program parse just fine:

``` cobol
IDENTIFICATION DIVISION.
PROGRAM-ID. TypeCobol.
PROCEDURE DIVISION.
copy CPY
.

IDENTIFICATION DIVISION.
PROGRAM-ID. TypeCobol.
PROCEDURE DIVISION.
copy CPY.
.

IDENTIFICATION DIVISION.
PROGRAM-ID. TypeCobol.
PROCEDURE DIVISION.
move a to b
copy CPY.
.
```

But the following program ends in error:

``` cobol
IDENTIFICATION DIVISION.
PROGRAM-ID. TypeCobol.
PROCEDURE DIVISION.
move a to b
copy CPY
.
```

[1,21:<missing SentenceEnd>]<HexadecimalNationalLiteral>{<missing SentenceEnd>}

You can see tests in:
`TypeCobol.Test/NewTestsToFix/Parser/Samples/HighPriority/CopyProcedure*.cbl`

_edited to add more info on the tests_

**Comment by smedilol** [comment]
When entering ProgramClassParserStep.ParseProgramOrClass method, codeElementsLines List contains one CodeElement for the copy statement. But the CodeElements for the statements inside the copy are absent.

**Comment by smedilol** [comment]
@laurentprudhon  can you look after this issue?

**Comment by laurentprudhon** [comment]
The following two lines in CodeElementsParserStep.ParseProcessedTokensLinesChanges() are incorrect :

> // Get the first line that was parsed
> CodeElementsLine codeElementsLine = ((CodeElementsLine)((Token)codeElementParseTree.Start).TokensLine);
> ...
> // Add code element to the list
> codeElementsLine.AddCodeElement(codeElement);

1. When the first Token of the current CodeElement (codeElementParseTree.Start) was found in an imported (COPY) file, codeElementsLine is a line of the imported (COPY) document, not a line of the mail (PROGRAM) document.
2. In this case, the codeElement object is added to a line of the COPY document, instead of a line of the PROGRAM document (this is the BUG !)
3. The next parsing step expects all CodeElements to be added to the main PROGRAM documents lines : it makes no sense to associate a CodeElement with a COPY document, because a CodeElement could perfectly span Tokens both inside and outside the COPY document.

Here is a recommended fix : 
1. Create a new class "ImportedToken", in the same namespace as ReplacedToken. ImportedToken has a constructor with two parameters : an original Token, and a CopyDirective. It is a thin wrapper over the original Token object (do not copy all fields, just forward properties get/set to the underlying Token), and defines an additional CopyDirective property. 
2. In CopyTokensLinesIterator, line 236 and line 294, return a new ImportedToken(nextImportedToken, copyDirective) instead of a raw nextImportedToken. 
3. CodeElementsParserStep, check the type of the Token codeElementParseTree.Start : 
- if Token, codeElementsLine = ((Token)codeElementParseTree.Start).TokensLine;
- if ImportedToken, codeElementsLine = ((ImportedToken)codeElementParseTree.Start).CopyDirective.TextNameSymbol.TokensLine;

This should also provide a solution for #259 : now we can check the type of the first token of the code element, and recursively get the CopyDirective property if it is an ImportedToken, to get the name of the COPY (or the nested COPIES) in which the first token of the code element was defined.

**Comment by smedilol** [comment]
Thanks @laurentprudhon

**Comment by smedilol** [comment]
PR #311 seems to fix this issue
