### ISSUE TITLE
Incremental bug : modification of CodeElement whose starting keyword is a target of a replace

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#2388]
**Describe the bug**
A CodeElement whose starting keyword is a target of a replace will create error in incremental mode.

**To Reproduce**
The example is unlikely to be a real code, but the bug happens when a starting keyword of a CodeElement is the target of a replace.
We have production code that do this kind of thing for call statement.
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. MyPGM.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 Var1 pic X.

       REPLACE ==:move:==           BY ==move==.
       PROCEDURE DIVISION.
           :move: Var1 to
           .
       END PROGRAM MyPGM.
```
Add a new line after `to` keyword and you'll get 3 errors::

- ```
  Runtime error: System.ArgumentException: Un élément avec la même clé a déjà été ajouté.

   à System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   à System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   à TypeCobol.Compiler.CupParser.NodeBuilder.ProgramClassBuilder.Enter(Node node, CodeElement context, SymbolTable table)
   à TypeCobol.Compiler.CupParser.NodeBuilder.ProgramClassBuilder.StartCobolProgram(ProgramIdentification programIdentification, LibraryCopyCodeElement libraryCopy)
   à TypeCobol.Compiler.CupParser.CUP_TypeCobolProgramParser_actions.CUP_TypeCobolProgramParser_do_action(Int32 CUP_TypeCobolProgramParser_act_num, lr_parser CUP_TypeCobolProgramParser_parser, StackList`1 xstack1, Int32 CUP_TypeCobolProgramParser_top)
   à TypeCobol.Compiler.CupParser.TypeCobolProgramParser.do_action(Int32 act_num, lr_parser parser, StackList`1 CUP_parser_stack, Int32 top)
   à TUVienna.CS_CUP.Runtime.lr_parser.parse()
   à TypeCobol.Compiler.Parser.ProgramClassParserStep.CupParseProgramOrClass(TextSourceInfo textSourceInfo, ISearchableReadOnlyList`1 codeElementsLines, TypeCobolOptions compilerOptions, SymbolTable customSymbols, PerfStatsForParserInvocation perfStatsForParserInvocation, ISyntaxDrivenAnalyzer[] customAnalyzers, SourceFile& root, List`1& diagnostics, Dictionary`2& nodeCodeElementLinkers, List`1& typedVariablesOutsideTypedef, List`1& typeThatNeedTypeLinking)```

- Syntax error : "END PROGRAM" is missing. on line 1
- Syntax error : "END PROGRAM" is missing on line 1

**Expected behavior**

Expected (Type)Cobol code : 
No errors.

**Technical**
Will be edited by a team member.
Implementation details with the chosen solution.

**How to test automatically**
Will be edited by a team member.
Only if our current automated tests doesn't handle this.

**Comment by fm-117** [comment]
### What happens:
- The `SeekToToken` method fails to find the starting token of the reparse section (here it is the replaced `move` token)
  - during equality comparison of `ReplacedToken.ReplacementToken`, the reference comparison for tokens lines returns `false`, this is most probably caused by the replace directive but I haven't checked.
- then we try to reparse whole document but we haven't correctly reset code elements on lines so we start duplicating code elements...
  - in debug however we first fail on an assertion ("Token not found in this stream")

### What to do:
- first we need to ensure that code elements are correctly reset when we fallback to full parsing
- secondly we could define a custom comparison mechanism for TokensLine so as to correctly identify start token
  - this could be costly as `Equals` operations are extremely frequent

Here is a patch file for the modification but it has to be discussed first.

[patch.diff.txt](https://github.com/TypeCobolTeam/TypeCobol/files/10261112/patch.diff.txt)
