### ISSUE TITLE
More typed AST

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#248]
*\* CHILD OF #203  **
Like discussed:
 The current Syntax Tree Node is not enough typed.
 The AST structure must follow a Cobol program structure.
 We should have:
•ProgramNode ◦IdentificationDivisionNode
◦DataDivisionNode
◦ProcedureDivisionNode ◾SectionNode ◾MoveNode
◾IfNode ....

We must alors separate CodeElement from Node:
 Currently DataDescrptionEntry is created during syntax parsing phase but reused between different semantic parsing phases. But some of its properties (like TopLevel) are set during semantic phase.
 This property must only be placed in a DataDescriptionEntryNode.

**Comment by smedilol** [comment]
Can methods of SymbolTable be more typed?
For example:
`public List<Node> GetFunction(QualifiedName name, ParametersProfile profile = null)`
Could be
`public List<FunctionDeclaration> GetFunctionDeclaration(QualifiedName name, ParametersProfile profile = null)`

`public List<Node> GetType(QualifiedName name)` could be `public List<TypeDefinition> GetTypeDefinition(QualifiedName name)`


`internal void AddVariable(Node symbol)` could be `internal void AddVariable(DataDefinition dataDefinition)`
`public List<Node> GetVariable(QualifiedName name)` could be `public List<DataDefinition> GetVariable(QualifiedName name)`
For variable, currently there are only DataDefinition added to SymbolTable, but shouldn't others things like symbolic characters be added too?

@wiztigers what do you think?

**Comment by wiztigers** [comment]
I think you ask two different questions, here [-ิ_•ิ]
I'll start with the last one :
* there are many "things" which are definitions but that are currently NOT added to `SymbolTable`. Among them yeah, there's symbolic characters, and anonymous data, and `FILLER` and paragraphs, and so on. To do all that, I only need the following things : specifications, issues and time. 
Currently I've got this huge specification, and the precise panorama of what remains to be added to the `SymbolTable` is burried inside it, so ... any help regarding analysis by some COBOL-guru passing by would be appreciated! Working alone I'll do it, but slower (^_−)☆
* regarding typing `SymbolTable` methods, it is theorically doable, but I'll waive some warning flags before you :
  * `SymbolTable` has currently 3 subtables : one for data, one for typedefs, one for functions. In your TypeCobol source code, you can have two items with the same name as long as they end in two different subtables.
  * As a corollary, two items going in the same `SymbolTable` subtable must be of the same type. Before merging branch `merge#249`, this type was just an interface `Named` ; now it's the `Node` class. Are you sure everything that cannot have a name conflict with something else is of the same type ? If you specialize these types too early (ie.: before having a clear vision of what remains to be added to the symbol table), it can come back and bite your nose later. That's why I began with just `Named` ... I hope everything will be Nodes ...
  * Of course, if you type more strongly a `SymbolTable.GetXXX` method, you must use the same stronger type in the corresponding `SymbolTable.AddXXX` method. This new specialized type will become the type for all values in the corresponding subtable.
  * This being said, I suppose specializing `[Add|Get]Type` and `[Add|Get]Function` as soon as now should be okay. But, for the love of the god of semantically naming and codelines which don't force you to use an horizontal scrollbar, please don't write something like `public List<FunctionDeclaration> GetFunctionDeclaration`, because you already said "FunctionDeclaration" in the return type, and because you won't store any other type of "Function" from the `SymbolTable` with no name conflict ... So, `GetFunction` is explicit enough, isn't it ? (´∀｀)✿
  * If you want this, please create a new issue. This one has been open for too long and should already be closed.

**Comment by smedilol** [comment]
To be discussed during a code review
