### ISSUE TITLE
Possibility to load multiple skeletons files 

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#286]
# Current context

TypeCobol is used to generate valid Cobol 85.
To do so, the project `CodeGen` use skeleton files that contains rules of transformation from TypeCobol to Cobol85.
e.g.: content of a skeleton file:

```
<skeleton name="TYPEDEF">
   <conditions>
     <condition node="TypeCobol.Compiler.CodeElements.DataDescriptionEntry" typedef="*"/>
   </conditions>
   <patterns>
      <pattern location="NODE" action="comment"></pattern>
   </patterns>
</skeleton>
```

This skeleton tells code generator to comment all nodes that are a DataDescriptionEntry.
You can see a full example here:
`Codegen.Test\resources\config\Types.xml`

Currently Command Line interface of TypeCobol only allow you to specify one skeleton file.
But to keep things clean, we choosed to create one skeleton file per concept of TypeCobol: Types, functions, procedures.

So we're currently merging all of our skeletons files into one.
# The need

What would be great is to specify a path with wildcard to load a full directory that contains skeletons files.
e.g. `SkeletonFolder\*.xml`
# Notes about implementation:

You can start modifications into `TypeCobol.Server.Server`
Current line that load one skeleton file is:
`var skeletons = TypeCobol.Codegen.Config.Config.Parse(config.skeletonPath);`
Variable `var skeletons` is of type `List<Skeleton>` and must contains `Skeleton` of each file specified in command line.

**Comment by wiztigers** [comment]
Rather than wildcarding like you propose, what about simply giving the skeletons loader a list of paths.
Then, for each path in the list:
1- if it's a file, check if it's a skeleton file ; if it is simply load it as is done now
2- if it's a firectory, search recursively all files contains and for each apply goto 1

I don't like much checking for extension to decide if a file is candidate for something. That's so windowsy !
Instead, what about using the file MIME type ? It's sufficient to check the first 256 bytes of the file, so it should be fast enough ... We've got an example of how it can be done in csharp [here](http://stackoverflow.com/questions/58510/using-net-how-can-you-find-the-mime-type-of-a-file-based-on-the-file-signature).
Then, you can tell a file is a skeleton file if :
- the file is of MIME type `text/xml` or `application/xml`
- the `ConfigParser` objects returns a non-empty list of skeletons (`XmlParser` should already be robust enough for this, provided you give it a real XML file, and not for example a binary blob with the `.xml` extension, a scenario that would probably be a problem with your proposal as is)

**Comment by smedilol** [comment]
We have issue #270, so for now I think the loading of different skeletons must be as fast as possible.
Checking the MIME type of a all files seems slow.

My proposition is not specific to extension, but to wildcard.

Even if you don't use extension, I assume you'll either put all your skeletons files in the same directory (then use `mySkelDir/*`) or use the same prefix for your skeletons (then use `skel-*`).

@wiztigers do you agree with this?

**Comment by wiztigers** [comment]
What makes you think that "checking the MIME type of a all files seems slow" ?
Although it wouldn't be a surprise that C# is, one more time, painfully slow for something everyone does right except windows, I'd prefer benchmarking this.

What I really think it we should just use stream as input, not files.
FWIW, I think @laurentprudhon applied it well in his design, as there is a preliminary step to make stream from files, and from then on we forget the notion of files alltogether.
Indeed, using stream as input allows an app to get its input for anywhere : for example, currently, I'm not sure we can use configuration files that are hosted remotely. If we want TypeCobol to run as a service hosted on a build server, using streams would be for me the way to go.

Hoovering a folder is better than reading a single file, yes. However, using any number of locations as streams, be they local files, remote files or something else entirely, beats them both in terms of flexibility and lasting quality IMHO.
And, when you don't know if your configuration file or something else, you can't use file extension.
