### ISSUE TITLE
Procedure: new features part 1/2

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#287]
New features for functions and procedures:
- [ ] Implement procedure as defined [here](https://github.com/TypeCobolTeam/TypeCobol/wiki/TypeCobolFunctions) and [here](https://github.com/TypeCobolTeam/TypeCobol/wiki/TypeCobolFunctionsSyntax)
- [ ] **TCRFUN_INPUT_ALL_BY** input parameters can be passed 'BY VALUE', 'BY CONTENT' or 'BY REFERENCE' [here](https://github.com/TypeCobolTeam/TypeCobol/wiki/TypeCobolFunctionsSyntax)
- [ ] **TCRFUN_INOUT_OUT_ONLY_BY_REFERENCE** inout and output parameters can only be passed by reference. [here](https://github.com/TypeCobolTeam/TypeCobol/wiki/TypeCobolFunctionsSyntax)
- [ ]  **TCRFUN_PARAMETER_MATCHING** The caller must provide the exact number of parameters and each parameter must match the type of function/procedure prototype. [here](https://github.com/TypeCobolTeam/TypeCobol/wiki/TypeCobolFunctionsSyntax)

Following rules have been removed from specifications:
- ~~**TCRFUN_DECLARATION_NO_REDEFINES**  `REDEFINES` are not allowed~~
- ~~**TCRFUN_DECLARATION_NO_RENAMES** `RENAMES` are not allowed~~
- ~~**TCRFUN_DECLARATION_NO_FILLER** `FILLER` are not allowed~~
- ~~**TCRFUN_DECLARATION_NO_ANONYMOUS_VARIABLES** Unnamed variables are not allowed~~

Make sure, it's not implemented anymore

**Comment by smedilol** [comment]
First set of new features for functions of procedure.
@wiztigers can you take check if everything it's clear for you and then implement this?

Thanks.

**Comment by wiztigers** [comment]
* **TCRFUN_INPUT_ALL_BY** was renamed in **TCRFUN_INPUT_BY** because a short concise name has less risks of error when typing or trying to recall a specific rule name.
* **TCRFUN_INOUT_OUT_ONLY_BY_REFERENCE** was renamed to **TCRFUN_CALL_INOUT_AND_OUTPUT_BY_REFERENCE** because the original name didn't inform about wheter this rule is about function invocation or declaration, because "OUT" doesn't exist as a keyword whereas `OUTPUT` does, and ONLY was redundant.
* **TCRFUN_PARAMETER_MATCHING** was rather a meta-rule, that was too vague for precise formulation and implementation progress tracking. So I replaced it by the following 5 rules:
  * **TCRFUN_CALL_PARAMETER_ORDER**
  * **TCRFUN_MATCH_PARAMETERS_NUMBER**
  * **TCRFUN_MATCH_PARAMETERS_TYPE**
  * **TCRFUN_MATCH_PARAMETERS_SIZE**
  * **TCRFUN_MATCH_PARAMETERS_COMPRESSION**

The 4 crossed rules at the end of the end of the issue description (**TCRFUN_DECLARATION_NO_REDEFINES REDEFINES**, **TCRFUN_DECLARATION_NO_RENAMES RENAMES**, **TCRFUN_DECLARATION_NO_FILLER FILLER** and **TCRFUN_DECLARATION_NO_ANONYMOUS_VARIABLES**) are nowhere to be seen either in source code, in test code or in the project wiki, and no other issue than this one references them, so there were never implemented, as far as I can trace.

The 7 new procedure invocation rules are now referenced on [this page](https://github.com/TypeCobolTeam/TypeCobol/wiki/FunctionsDeclaration).
When any rules referenced on this page has to be modified, or if rules must be added, we *MUST* open a corresponding issue to each rule, because I cannot warrant the proper rule implementation if anyone modifies the wiki behind my back with no traceability.

**Comment by wiztigers** [comment]
I've implemented every rule that I could grasp.
That is, every rule excepted **TCRFUN_MATCH_PARAMETERS_COMPRESSION** which I thus consider unproperly specified.
I've created a dedicated issue #335.

**Comment by smedilol** [comment]
I'll check these new rules
