### ISSUE TITLE
Forbid REPLACE and Function/Procedure

### ISSUE THREAD

**Issue by osmedile** [TypeCobolTeam/TypeCobol#320]
TypeCobol function and procedure use the action "expand" of Codegen to move Nodes to a new parent.

If you write REPLACE in your code:
Example:

``` cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. DVZZDATE.
       DATA DIVISION.
           REPLACE ==:MyReplace:== by ==1==.
       PROCEDURE DIVISION.
       DECLARE PROCEDURE test PUBLIC.
       PROCEDURE DIVISION.
           display :MyReplace:
           .
       END-DECLARE.
       REPLACE ==:MyReplace:== by =="2"==.
       END PROGRAM DVZZDAT.
```

The generated code is :

``` cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. DVZZDATE.
       DATA DIVISION.
           REPLACE ==:MyReplace:== by =="1"==.
       PROCEDURE DIVISION.
           SET test TO ENTRY 'F0000001'
           .
*=================================================================
      *DECLARE PROCEDURE test PUBLIC.                                                        
      *_________________________________________________________________
       REPLACE ==:MyReplace:== by =="2"==.
       END PROGRAM DVZZDAT.
      *_________________________________________________________________      
       IDENTIFICATION DIVISION.                                               
       PROGRAM-ID. F0000001.                                             
       DATA DIVISION.                                                         
       LINKAGE SECTION.                                                       
       01 Result.                                                             
           02 YYYY PIC 9(4).                                                  
           02 MM PIC 9(2).                                                    
           02 DD PIC 9(2).                                                    
       PROCEDURE DIVISION.                                  
           display :MyReplace:
           .
       END PROGRAM F0000001.                                 
```

You expect to display 1 when writing your TC code...

A fix can be to search the last REPLACE before every Function/Procedure declaration and write it again before the `IDENTIFICATION DIVISION` of the Function/Procedure...

~@wiztigers @reydelpa what do you think?~

~EDIT: 
new rule: If f there is one action of Codegen that move node (location !="NODE" in XML config file), then Replace directive is forbidden.~

EDIT 2:
There is too many use of `Replace` in our company, we can't forbid it in TypeCobol.
So currently what is described here will be listed as a potential problem of TypeCobol.

**Comment by wiztigers** [comment]
Problem is, currently I have no easy way of detecting _any_ preprocessor statement. These (along with blank lines, debug lines and comments) are outside of the CodeElements parser business, because preprocessor statements instead _modify_ the CodeElements parser input.

Thus, as a preprocessor statement cannot currently become a `Node`, I cannot easily implement the behaviour you describe. This is why I must resort to kinda-hacky-aftertough tricks like what is done in `TreeToCode.WriteInputLinesUpTo`, which boils down to a textual analysis of the source code, which is a shame to be done in C# as this kind of work should be done by ANTLR. The fix you describe at the end of your post is kinda like that, and "could" theorically be done.
This would be, however, one more hack and, honestly too much a hassle for what it's worth IMO. Which is a omen telling us we need to improve our pipeline.

What would be neat would be to have a way to create something like a `NonSourceCodeNode`, which could be plainly ignored by semantic analysis (excepted maybe debug lines depending on parser settings).
On the other hand, Codegen could use such a node in the two following ways :
- copy it "as is" in the generated output (if it is a standard comment or blank line)
- use its children for specific feature, like "if a function declaration in the TypeCobol input tree contains a preprocessor statement or a comment line `Node`, move it as a child of the corresponding subprogram node" in the COBOL output tree.

Yeah, I'd need something like that.
@laurentprudhon , is this realistic ?

**Comment by smedilol** [comment]
After discussing with Laurent, yes it's possible.
In Roslyn compiler, comment are called "trivia".

We can plan to add Debug lines and comment in our AST for next year (new issue to create)

After discussing with Patrick we agreed to forbid it for now.

The rule is: if there is one action of Codegen that move node, Replace directive is forbidden.

**Comment by smedilol** [comment]
Codegen now handle CompilerDirective (like Replace) correctly.
The only problem left is what is described on the first comment.
It'll be described as a potential problem of TypeCobol for now.

**Comment by smedilol** [comment]
Won't  implement as TypeCobol language is no longer supported.
