### ISSUE TITLE
Bool codegen template is duplicated: in skeleton and in C#

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#360]
Bool codegen is duplicated:

- In skeleton
- In ParameterEntry

**Comment by wiztigers** [comment]
Yeah, I know.
You sure have noticed my *TODO* remark in `ParameterEntry`, didn't you ? ★＝(−.⌒)

Currently we don't really have a fast way to refactor this. In particular, refactoring this would be linked to what you analysed in #339, namely refactoring function and method declaration parameters into `CodeElements`. A boolean CodeElement could thus have its own codegen, where it would generate with the `-value` prefix AND generate the proper COBOL declare in the current scope's `LINKAGE SECTION`.
However ... this is faster said than done and is not exactly the way codegen currently works (with our AST branches stopping at statement-level n'stuff).

Anyway, you'll notice a lot of these kind of "this would be nice to refactor" issues if you `grep TODO` in our project. I didn't create issues for all this because such issues descriptions would sooner or later be totally out of date, because of our current R&D stance. And I already did such refactors over time, when "it was the right moment".
So ... what should I do with this particular issue ? Do we create a "refactor" tag and link "refactor" issues to a tantalizingly unreachable milestone or what ? (^^; )

**Comment by smedilol** [comment]
TypeCobol is abandonned, this issue is not needed anymore.
