### ISSUE TITLE
Upgrade test engine

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#39]
* One must be able to just put a *.cbl* source file somewhere under *TypeCobol.Test/Compiler/Parser/Samples* and a *.txt* expected results file somewhere under *TypeCobol.Test/Compiler/Parser/ResultFiles*.
* The unit test engine should find the two files (provided the result file has the same filename without extension as the source file), parse the *.cbl* file and compare it against the contents of the *.txt* file.
* The contents of the expected result files should not be too hard to write, and as lisible as possible. In particular, expected results should be written/read sequentially, line by line.

**Comment by osmedile** [comment]
In order to ease tests writing, it should be useful to have only one file to describe tests cases.
In this file you could write the statements to test, if this statement is expected to be parsed correctly and then the expected processed statement.
Ex:
Ok: add a to b -> add a to b      *> the test statement and processed statement are identical
Ok: add a to b                           *> same test as above. In this case the expected statement will be equals to the statement to test
Ko: add to b                             *> Parsing error expected
OK: add toto     titi tata to X -> add toto titi tata to X          *> in the processed statement all redundant spaces are trimmed

This kind of test could be written by Cobol developper without knowledge of the TypeCobol parser.

**Comment by wiztigers** [comment]
I think the form given to a specific result file could be given by its name.
For example, corresponding to source cobol file named `ADD.cbl` (put in `Samples\Statements` folder), could be (in `ResultFiles\Statements` folder) :
* `ADDCodeElements.txt`, containing the CodeElement.ToString() calls as we know it
* `ADDRPN.txt`, containing the conversion to Reverse Polish Notation strings
* `ADDNY.txt`, containing just "Y" or "N" depending of the correct (or incorrect) parsing of each line
* whatever else we think of

For a given cobol file, the test engine could find all files beginning with `ADD`, deciding wich comparison happens by looking at the suffix, and defaulting to CodeElement comparison if it only finds `ADD.txt` as a result file.
If no result file is to be found, an error would be thrown.

This solution is more flexible that what we have, but would prevent having for example the files `ADD.cbl` and `ADDErrors.cbl` in the same folder. We should have `ADDSuccesses.cbl` and `ADDErrors.cbl` instead.

**Comment by wiztigers** [comment]
Since a few months, test engine automatically test files in _subfolders of_ `TypeCobol.Test/Compiler/Parser/Samples` and compare results with expected result files in _subfolders of_ `TypeCobol.Test/Compiler/Parser`.
Different comparators can be used, depending of the name of a given result file.
You can create more than one expected result file for a given sample file if you want to run different comparators for the same sample.

Let's say it's enough to close this issue.
Create other issue if additional needs arise.
