### ISSUE TITLE
Continuation line

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#457]
Fix the test
`TypeCobol.Test\NewTestsToFix\Parser\Samples\MidPriority\MultiLines.rdz.cbl`
and move it to Cobol85 standard test folder.

**Comment by collarbe** [comment]
It appears that if we add a space after the first ' symbol, the test pass without problem. We have to verify what does the IBM Cobol compiler.

**Comment by smedilol** [comment]
After some tests:
The original issue is resolved, but I noticed that existing tests are in fact wrong.
I'd like to review all tests about continuation line before merging this PR

**Comment by smedilol** [comment]
@fm-117  Can you check if the fix on #1777, resolve this issue ?

**Comment by fm-117** [comment]
About `TypeCobol.Test\NewTestsToFix\Parser\Samples\MidPriority\MultiLines.rdz.cbl`, the source is already includded as a Cobol85 test but it is tested against FreeReferenceFormat. Using CobolReferenceFormat, the parser fails completely as scanner produces duplicate tokens.
This is in fact related to #1791 because we omit spaces in value of line 12 and then we use positions to add tokens to each line. As the virtual line is smaller than expected, some tokens are added twice, once on the continued line, and then again on the continuation line.
