### ISSUE TITLE
Clarify usage of Node.ID Node.Name Node.QualifiedName Node.GenURI

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#474]

**Comment by mayanje** [comment]
For the issue #447 It was "necessary" to introduce the new method GenURI, for the generator to access to a node whose path is like "program.procedure-division.paragraph". The URI property for Paragraph node is the paragraph's name, this cannot be an access path for the Generator.

**Comment by collarbe** [comment]
TODO : 
Name doesn't have to return ID, by default it has to retrun an empty string. 
ID doesn"t have to return Name. 
Change all ID override that does not return a string of node type. 
Modify GenGet() to use URI and not GenURI
Delete GenURI filed
Take deeper a look at QualifiedName on Node.cs

**Comment by collarbe** [comment]
Note : Removing CodeElement.Name return for ID. 

- Change ID to return "paragraph" but URI is based on ID, and QualifiedName is based on URI. Qualified name is for instance used in SymbolTable Add<T>(). It creates duplicated element beacuse we can have multiple pararaph... 
- Solution idea : is to override QualifiedName in Parapgrah node and return URI(this.Name) instead of URI(this.ID)....

**Comment by collarbe** [comment]
Have to work on `QualifiedName`: sometime Name is used and sometime ID..

**Comment by smedilol** [comment]
Ok, except one thing:
why have a Property `NameURI` on Node?
Can you do all the work directly in QualifiedName?

**Comment by collarbe** [comment]
I tryed to remove NameURI and only use QualifiedName property to get the full name of a parent also based on QualifiedName but it creates dramatic low performance on NistTest.

I need to resolve the entire parent name with all his parents in order to track the current node. If I don't have NameURI, I'm forced to use QualifiedName.
