### ISSUE TITLE
Some diagnostics appear in our client but they are not related to the current edited source

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#623]
Ideas:
- Incremental mode is not working well and the text parsed is not accurate
- Our implementation of LanguageServer protocol has a bug, and the client/server exchange wrong text

**Comment by mayanje** [comment]
The following file makes the the TypeCobol.LanguageServer incremental parsing goes in a infinite ANTLR parsing loop. This happens when in the TypeCobol.Language Client the following sequence is comment/uncomment line by line in a random sequence.

       EXEC SQL
         INCLUDE SQLCA
       END-EXEC.


[BugExecSql.txt](https://github.com/TypeCobolTeam/TypeCobol/files/1194371/BugExecSql.txt)

**Comment by smedilol** [comment]
Note that you can write incremental test. See test in class  `TestIncrementalPipeline`

**Comment by smedilol** [comment]
Following our last meeting, we can implement this mechanism:

The client is currently sending an event with the text change.
It can attach its whole text document.


Then the server will rebuild the whole text thanks to the text change.
The server can then compare if the rebuilt text is equals to the original text sent by the client.

**Comment by collarbe** [comment]
After some tests, it seems that the source text managed by the server and the source text managed by the editor are the same. 

Regarding to the diagnostics, I figure out that we are always having the issue #605. ANTLR is always generating diagnostics on the next significant line of code.  (Also linked to #611)


```COBOL
CAL *No diags here*
MOVE var1 TO var2 *Diags will be on this line*
```
```COBOL
CAL *No diags here*
*No diags here*
MOVE var1 TO var2 *Diags will also be on this line*
```

Lastly, I also figured out the origin of diagnostics targeting DATA DIVISION and END PROGRAM. This diags happens when the Code Elements are duplicated. During the incremental process, if no real changes are detected, it seems that _ParseProcessedTokensLinesChanges()_ (CodeElementParserStep.cs) is duplicating Code Element per line.

**Comment by mayanje** [comment]
Leave a comment
