### ISSUE TITLE
Some times completion doen't work

### ISSUE THREAD

**Issue by collarbe** [TypeCobolTeam/TypeCobol#626]
Need to investigate. 

May it comes from the client, may it comes from the server.

**Comment by mayanje** [comment]
collarbe: It will be nice to test again, this issue again, because I noticed that if for any reason the result of request from teh server is null, then for the client this is an abnormal situation, because a request should return a valid response or an error code. So in the client I made a change to simply log any null response and not throwing an abnormal exception.

**Comment by mayanje** [comment]
I close this issue because it is now too general, we must create a new task to validate our LSP protocol implementation, there is  an LSR issue to support LSP 2.x and to validate it: https://github.com/TypeCobolTeam/LanguageServerRobot/#39
