### ISSUE TITLE
Empty source files

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#73]
Currently, our parser cannot take completely empty source files as an input: it breaks with the following error:
`[1,0]<28,Error,Syntax>Syntax error : no viable alternative at input '<EOF>' (RuleStack=codeElement, OffendingSymbol=[1,0:]<EndOfFile> on line 0)`

However, our syntax explicitely says a file can be empty:
```cobol
cobolCodeElements:
    codeElement* EOF;
```
So, what's the matter?

Take a look at 05e6898965f479e539219fc3b9241240ee1aea04: OPEN sample and result file are empty, but the test fails.

**Comment by wiztigers** [comment]
rewriting the starting rule as:
```cobol
cobolCodeElements:
    EOF | (codeElement* EOF);
```
has no effect. Neither has adding an empty line in sample file ... *(scratches head)*

**Comment by laurentprudhon** [comment]
That's because the rule cobolCodeElements is not used in SyntaxDocument.
In SyntaxDocument.cs, line 102, you find the following statement in a loop :
CobolCodeElementsParser.CodeElementContext codeElementParseTree = cobolParser.codeElement();
We wrote this because we want to be able to collect individual CodeElements in a list, which is updated incrementally.
The solution is to introduce a new rule codeElementOrEmpty in the grammar, add a ? behind codeElement, and call this new rule in SyntaxDocument.

**Comment by wiztigers** [comment]
SyntaxDocument.cs doesn't exist anymore since 1ca12090a6be993b0e835a0bdc382ddd58ee23e1 #115.
As of today, empty files don't raise any error ; I guess it's a nice side effect of this big PR.

**Comment by wiztigers** [comment]
ac3a838e3c89c566209719ece305df2db9c8dd16 shows that this problem is not solved, after all.
