### ISSUE TITLE
Compilation options are not manage in the transform file

### ISSUE THREAD

**Issue by collarbe** [TypeCobolTeam/TypeCobol#932]
Option like CBL LIST .... has to be declared in the first line of any source. In our case the Transform project does not manage this king of situation and will not place the CBL at the top of the transformed file containing the parts. 

What we get now : 
![image](https://user-images.githubusercontent.com/25581246/39619067-b6ed8b9c-4f86-11e8-9175-4f9581bd2247.png)

It should be like this :
![image](https://user-images.githubusercontent.com/25581246/39619088-c917c1c0-4f86-11e8-920b-46b1ea077574.png)

The commented line for CBL options also has to be removed from the commented TypeCobol source : 
![image](https://user-images.githubusercontent.com/25581246/39620699-498ae954-4f8c-11e8-9159-bd1f003d7931.png)

**Comment by mayanje** [comment]
According to IBM Enterprise Cobol 5.1 for zOS - Language Reference.pdf a line  CBL statement can be preceed by a sequence number in columns 1 through 6, so StartsWith cannot be used to check if a line is a CBL one. So something like a Regular expression must be used.

**Comment by mayanje** [comment]
*CONTROL (*CBL) statements are also allowed where CBL is allowed.

**Comment by smedilol** [comment]
Note:
Commit f4cfd24da3c383a30717ed20c67c108e09e018e9 reverted 1916be1502215f8e7755bde77da39ae1fa7819fa because it was no the good way to resolve the issue.

Commit f4cfd24da3c383a30717ed20c67c108e09e018e9 has been applied to master branch, but not on the develop branch (at least not until today).

The unit tests done in original commit 1916be1502215f8e7755bde77da39ae1fa7819fa are now done in different unit test. See commit 28c4a75b8ae511352207ad2ea7b50b7965bd6274 (on both develop and master branch).
