### ISSUE TITLE
Populate StorageAreaReads and StorageAreaWrites for MOVE CORR

### ISSUE THREAD

**Issue by cobarzanc** [TypeCobolTeam/TypeCobol#979]
The StorageAreaReads and StorageAreaWrites properties on the node containing the MOVE CORR statement are not set. 

In order to keep the code consistency they should be set. It will also streamline issue #967

**Comment by smedilol** [comment]
My mistake about what I asked you.
Finally we cannot use StorageAreaReads and StorageAreaWrites to store StorageArea of CORRESPONDING clause (property storageAreaGroupsCorrespondingImpact).
Because a CORRESPONDING clause only read/write on certain children of the variable referenced.

As discussed before, the Dictionary at the Node level for #967 will contains StorageArea read/write of storageAreaGroupsCorrespondingImpact.

This is not exactly right, but it'll be treated in another issue.
